// +build gofuzz

package tlsutil

/*
	This is a wrapper function for https://github.com/dvyukov/go-fuzz to fuzz this package
	---
	To run it, check the README.md of that project since it may have changed
*/

func Fuzz(data []byte) int {
	/*
		Data is a random input generated by go-fuzz, note that in most cases it is
		invalid. The function must return 1 if the fuzzer should increase priority of
		the given input during subsequent fuzzing (for example, the input is lexically
		correct and was parsed successfully); -1 if the input must not be added to
		corpus even if gives new coverage; and 0 otherwise; other values are reserved
		for future use.
	*/
	_, err := ValidateClientHello(data)
	if err != nil {
		return 0
	}
	return 1
}
